#!/bin/bash

for repo in $(
  curl -H "Authorization: bearer $ZAMPLES_GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v4.idl" \
  -d '{ "query":"{ search(type: REPOSITORY, first: 100, query: \"org:near-examples\") { nodes { ... on Repository { name } } } }"}' \
  https://api.github.com/graphql \
  | jq -r '.data.search.nodes[].name'
); do
  printf "\n\n========== pulling latest \e[1;34m$repo:master\e[0m ==========\n"

  if test -d "./$repo"; then
    cd $repo
    if [[ master != `git branch --show-current` ]]; then
      printf "\n\n\e[1;31mSKIPPING\e[0m, not on master\n"
      git status
    elif [[ `git status --short | wc -c` -ne 0 ]]; then
      printf "\n\n\e[1;31mSKIPPING\e[0m, working tree not clean \n"
      git status
    else
      git pull origin master
    fi
    cd ..
  else
    hub clone near-examples/$repo
  fi
done
