#!/bin/bash

ORG=near-examples

for repo in $(
  curl https://api.github.com/orgs/$ORG/repos \
  | jq -r '.[].name'
); do
  if test -d "./$repo"; then
    printf "\n\n========== pulling latest \e[1;34m$repo\e[0m ==========\n"

    cd $repo
    if [[ master != `git branch --show-current` ]]; then
      printf "\n\n\e[1;31mSKIPPING\e[0m, not on master\n"
      git status
    elif [[ `git status --short | wc -c` -ne 0 ]]; then
      printf "\n\n\e[1;31mSKIPPING\e[0m, working tree not clean \n"
      git status
    else
      git pull origin master
    fi
    cd ..
  else
    printf "\n\n========== cloning \e[1;34m$repo\e[0m ==========\n"

    hub clone $ORG/$repo
  fi
done
