#!/bin/bash

OTHER=""

for repo in  *; do
  cd "$repo" || return;
  if [[
    master != $(git rev-parse --abbrev-ref HEAD) ||
    $(git status --short | wc -c) -ne 0
  ]]; then
    OTHER=" other"
    printf "========== \e[1;34m%s\e[0m ==========\n" "$repo";
    git status
    printf "\n\n";
  fi
  cd ..
done

if [[ $OTHER != "" ]]; then
  printf "==================================\n\n"
fi
printf "\e[1;32mAll%s projects on clean master\e[0m\n" "$OTHER"
